linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - forbidigo # might want to reconsider
    - gomnd
    - gci
    - goimports
    - golint
    - maligned
    - scopelint
    - wsl
    - interfacer

service:
  golangci-lint-version: 1.41.x