run:
  tests: false
linters:
  enable-all: true
  disable:
     - exhaustivestruct
     - golint
     - maligned
     - scopelint
     - wsl
     - interfacer
     - godox
     - gomnd

service:
  golangci-lint-version: 1.41.x