apiVersion: kuttl.dev/v1beta1
kind: TestSuite
kindContainers:
  - babylon:latest
testDirs:
  - tests/e2e/
manifestDirs:
  - tests/before/
kindNodeCache: true
artifactsDir: kuttl-logs
reportFormat: JSON
commands:
  - command: kubectl wait --timeout=60s --for condition=ready nodes --all
  # TODO: sleep here does not work and the resources are created to quickly before this, race conditions :)
  - command: sleep 5
  - command: kubectl wait --timeout=60s --for condition=ready pod -l app=babylon-test --namespace=babylon-test
timeout: 60
parallel: 8