apiVersion: apps/v1
kind: Deployment
metadata:
  name: babylon-minikube
  labels:
    app: babylon-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: babylon-minikube
  template:
    metadata:
      labels:
        app: babylon-minikube
    spec:
      serviceAccountName: babylon-service-account
      containers:
        - name: babylon-minikube
          imagePullPolicy: Never
          env:
            - name: ARMED
              value: "true"
            - name: RESTART_THRESHOLD
              value: "3"
            - name: LINKERD_DISABLED
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: RESOURCE_AGE
              value: "60s"
            - name: TICKRATE
              value: "10s"
            - name: NOTIFICATION_TIMEOUT
              value: "60s"
          image: babylon
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-cluster-role
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - "services"
      - "endpoints"
      - "pods"
      - "deployments"
      - "replicasets"
    verbs:
      - "get"
      - "delete"
      - "list"
      - "watch"
      - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: babylon-cluster-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: babylon-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: babylon-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: babylon-service
spec:
  selector:
    app: babylon-minikube
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: babylon-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: babylon.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: babylon-service
                port:
                  number: 8080