apiVersion: apps/v1
kind: Deployment
metadata:
  name: babylon-minikube
  labels:
    app: babylon-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: babylon-minikube
  template:
    metadata:
      labels:
        app: babylon-minikube
    spec:
      serviceAccountName: babylon-service-account
      containers:
        - name: babylon-minikube
          imagePullPolicy: Never
          env:
            - name: ARMED
              value: "true"
            - name: RESTART_THRESHOLD
              value: "3"
            - name: LINKERD_DISABLED
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: RESOURCE_AGE
              value: "60s"
            - name: TICKRATE
              value: "10s"
            - name: NOTIFICATION_TIMEOUT
              value: "60s"
            - name: USE_ALLOWED_NAMESPACES
              value: "true"
            - name: ALLOWED_NAMESPACES
              value: "default,babylon-test"
            - name: CLUSTER
              value: "minikube"
            - name: AIVEN_INFLUXDB_SERVICE_URI
              value: "http://influxdb-service:8086"
            - name: AIVEN_INFLUXDB_DATABASE
              value: testdb
            - name: AIVEN_INFLUXDB_USERNAME
              value: admin
            - name: AIVEN_INFLUXDB_PASSWORD
              value: admin
          image: babylon
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: babylon-working-hours
            items:
              - key: "working-hours.yaml"
                path: "./working-hours.yaml"
---
apiVersion: v1
kind: ConfigMap
data:
  "working-hours.yaml": |
    - name: working-hours
      time_intervals:
        - weekdays: ["monday:friday"]
          times:
          - start_time: 10:00
            end_time: 17:00
metadata:
  name: babylon-working-hours
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-cluster-role
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - "services"
      - "endpoints"
      - "pods"
      - "deployments"
      - "replicasets"
    verbs:
      - "get"
      - "delete"
      - "list"
      - "watch"
      - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: babylon-cluster-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: babylon-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: babylon-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: babylon-service
spec:
  selector:
    app: babylon-minikube
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: babylon-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: babylon.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: babylon-service
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-minikube
  labels:
    app: influxdb-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-minikube
  template:
    metadata:
      labels:
        app: influxdb-minikube
    spec:
      containers:
        - name: influxdb-minikube
          image: influxdb:1.8
          env:
            - name: INFLUXDB_DB
              value: testdb
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 8086
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: influxdb.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: influxdb-service
                port:
                  number: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb-minikube
  ports:
    - port: 8086
      targetPort: 8086
---