apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: babylon-alerter
  namespace: aura
  labels:
    team: aura
spec:
  route:
    group_by: [slack_channel]
    repeatInterval: 12h
  receivers: # receivers for all alerts below
    slack:
      channel: '\{{ index ((index .Alerts 0).Labels) "slack_channel" }}'
      icon_emoji: ':farmer:'
      send_resolved: false
      username: Babylon
  alerts:
    - alert: Rollout av feilende applikasjon avbrutt
      expr: 'babylon_deployment_cleanup_total{reason="rollback",dry_run="false"}'
      for: 0s
      description: |
        Vi har håndtert en feil i NAIS-deploymentet "\{{ $labels.deployment }}".
        Det har gått minst 24 timer siden dere først ble varslet.
        Siden deploymentet hadde minst en fungerende
        pod fra en tidligere revisjon, har det blitt utført en abort-rollout.
      action: |
        Slå applikasjonen av og på igjen eller slett den.

        Kan også være nyttig å:
        - Lese app logs (kubectl logs appname).
        - Lese Application events (kubectl describe deployment appname)

        Om du ønsker å motta disse meldingene i en annen kanal,
        kan du legge til en annen kanal i `platform-alerts-channel`-feltet i
        https://github.com/navikt/teams.
        Vi prioriterer også eksisterende kanaler brukt i en NAIS-alert i samme
        namespace, i alfabetisk rekkefølge.
      documentation: https://github.com/nais/babylon/README.md
      severity: warning
    - alert: Feilende applikasjon detektert
      # this is basically just joining the most recent `slack_channel` into the metric,
      expr: |
        (increase(babylon_deployment_status_total[2m]) > 10)
        * on (deployment, namespace, affected_team)
        group_left(slack_channel)
        (group without ()
        (topk by (deployment, namespace, affected_team) (1, babylon_slack_channel)))
      for: {{ notification_delay }}
      description: |
        Vi har detektert at NAIS-deploymentet "\{{ $labels.deployment }}" har feilet over en lengre periode.
        \{{- if eq $labels.dry_run "false" }}
        Dersom dere ikke utfører endringer, vil Babylon nedskalere eller avbryte rollout av
        applikasjonen tidligst om 24 timer.
        Merk at ingenting vil skje utenfor normal arbeidstid.
        \{{- else }}
        Babylon er ikke armert i klusteret som applikasjonen kjører i, og vil derfor ignorere ressursen.
        \{{- end}}
      action: |
        Slå applikasjonen av og på igjen, utfør `rollback`,
        eller slett applikasjonen.

        Kan også være nyttig å:
        - Lese app logs (kubectl logs appname).
        - Lese Application events (kubectl describe deployment appname)

        Om du ønsker å motta disse meldingene i en annen kanal,
        kan du legge til en annen kanal i `platform-alerts-channel`-feltet i
        https://github.com/navikt/teams.
        Vi prioriterer også eksisterende kanaler brukt i NAIS-alerts i samme
        namespace, i alfabetisk rekkefølge.
      documentation: https://github.com/nais/babylon/README.md
      severity: warning
    - alert: Feilende applikasjon nedskalert
      expr: 'babylon_deployment_cleanup_total{reason="downscale",dry_run="false"}'
      for: 0s
      description: |
        Vi har håndtert en feil i NAIS-deploymentet "\{{ $labels.deployment }}".
        Det har gått minst 24 timer siden
        dere først ble varslet, og deploymentet er nå skalert ned til 0 replicas.
      action: |
        Slå applikasjonen av og på igjen, utfør `rollback`,
        eller slett applikasjonen.

        Kan også være nyttig å:
        - Lese app logs (kubectl logs appname).
        - Lese Application events (kubectl describe deployment appname)

        Om du ønsker å motta disse meldingene i en annen kanal,
        kan du legge til en annen kanal i `platform-alerts-channel`-feltet i
        https://github.com/navikt/teams.
        Vi prioriterer også eksisterende kanaler brukt i en NAIS-alert i samme
        namespace, i alfabetisk rekkefølge.
      documentation: https://github.com/nais/babylon/README.md
      severity: warning
---
apiVersion: nais.io/v1
kind: Alert
metadata:
  name: babylon-down-alert
  namespace: aura
  labels:
    team: aura
spec:
  receivers:
    slack:
      channel: 'babylon-existential-alerts'
      icon_emoji: ':heart:'
  alerts:
    - alert: applikasjon nede
      expr: kube_deployment_status_replicas_available{deployment="babylon"} == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="babylon",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="babylon"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
---
apiVersion: nais.io/v1
kind: Alert
metadata:
  name: babylon-alerts-backup
  namespace: aura
  labels:
    team: aura
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: babylon-alerts-backup
      icon_emoji: ':robot_face:'
      send_resolved: false
      username: Babylon Backup Responsible
  alerts:
    - alert: Rollout av feilende applikasjon avbrutt
      expr: 'babylon_deployment_cleanup_total{reason="rollback",dry_run="false"}'
      for: 0s
      description: |
        Babylon har varlset i kanal "\{{ $labels.slack_channel }}" for deployment "\{{ $labels.deployment }}"
        i namespace "\{{ $labels.namespace}}" (team: \{{ $labels.affected_team }}). Siden deploymentet hadde minst en fungerende
        pod fra en tidligere revisjon, har det blitt utført en abort-rollout.
      action: Ignore this message
      documentation: https://github.com/nais/babylon/README.md
      severity: warning
    - alert: Feilende applikasjon detektert
      # this is basically just joining the most recent `slack_channel` into the metric,
      expr: |
        (increase(babylon_deployment_status_total[2m]) > 10)
        * on (deployment, namespace, affected_team)
        group_left(slack_channel)
        (group without ()
        (topk by (deployment, namespace, affected_team) (1, babylon_slack_channel)))
      for: {{ notification_delay }}
      description: |
        Babylon har varlset i kanal "\{{ $labels.slack_channel }}" for deployment "\{{ $labels.deployment }}"
        i namespace "\{{ $labels.namespace}}" (team: \{{ $labels.affected_team }}).
        \{{- if eq $labels.dry_run "false" }}
        Babylon er armert i klusteret.
        \{{- else }}
        Babylon er ikke armert i klusteret.
        \{{- end}}
      action: Ignore this message
      documentation: https://github.com/nais/babylon/README.md
      severity: warning
    - alert: Feilende applikasjon nedskalert
      expr: 'babylon_deployment_cleanup_total{reason="downscale",dry_run="false"}'
      for: 0s
      description: |
        Babylon har varlset i kanal "\{{ $labels.slack_channel }}" for deployment "\{{ $labels.deployment }}"
        i namespace "\{{ $labels.namespace}}" (team: \{{ $labels.affected_team }}).
      action: Ignore this message
      documentation: https://github.com/nais/babylon/README.md
      severity: warning
