apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "babylon"
  namespace: "babylon"
  labels:
    "team": "babylon"
spec:
  image: {{image}}
  env:
    - name: LOG_LEVEL
      value: "{{log_level}}"
    - name: PORT
      value: "{{port}}"
    - name: ARMED
      value: "{{armed}}"
  liveness:
    path: "/healthz"
    port: 8081
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/readyz"
    port: 8081
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
      {{/each}}