apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "babylon"
  namespace: "babylon"
  labels:
    "team": "babylon"
spec:
  image: {{image}}
  env:
    - name: LOG_LEVEL
      value: "{{log_level}}"
    - name: PORT
      value: "{{port}}"
    - name: ARMED
      value: "{{armed}}"
    - name: ALERT_CHANNELS
      value: "{{alert_channels}}"
    - name: RESTART_THRESHOLD
      value: "{{restart_threshold}}"
    - name: RESOURCE_AGE
      value: "{{resource_age}}"
    - name: TICKRATE
      value: "{{tickrate}}"
    - name: NOTIFICATION_TIMEOUT
      value: "{{notification_timeout}}"
    {{#if linkerd_disabled}}
    - name: LINKERD_DISABLED
      value: "{{linkerd_disabled}}"
    {{/if}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: 200m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 4Gi
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
      {{/each}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: babylon
    team: babylon
  name: babylon-apiserver
  namespace: babylon
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.64.1/32
        - ipBlock:
            cidr: 172.16.0.2/32
  podSelector:
    matchLabels:
      app: babylon
  policyTypes:
    - Egress