apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "babylon"
  namespace: "babylon"
  labels:
    "team": "babylon"
spec:
  image: {{image}}
  env:
    - name: LOG_LEVEL
      value: "{{log_level}}"
    - name: PORT
      value: "{{port}}"
    - name: ARMED
      value: "{{armed}}"
    - name: RESTART_THRESHOLD
      value: "{{restart_threshold}}"
    - name: RESOURCE_AGE
      value: "{{resource_age}}"
    {{#if use_allowed_namespaces}}
    - name: USE_ALLOWED_NAMESPACES
      value: "{{use_allowed_namespaces}}"
    - name: ALLOWED_NAMESPACES
      value: "{{allowed_namespaces}}"
    {{/if}}
    - name: TICKRATE
      value: "{{tickrate}}"
    {{#if unleash_url}}
    - name: UNLEASH_URL
      value: "{{unleash_url}}"
    {{/if}}
    - name: NOTIFICATION_TIMEOUT
      value: "{{notification_timeout}}"
    {{#if linkerd_disabled}}
    - name: LINKERD_DISABLED
      value: "{{linkerd_disabled}}"
    {{/if}}
    - name: CLUSTER
      value: "{{cluster}}"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  influx:
    instance: influx-nais
  resources:
    limits:
      cpu: 200m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 4Gi
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
      {{/each}}
  filesFrom:
    - configmap: babylon-working-hours
      mountPath: "/etc/config"
  {{#if in_gcp_cluster}}
  envFrom:
    - secret: "aiven-influxdb-service-uri"
  {{/if}}
---
apiVersion: v1
kind: ConfigMap
data:
  "working-hours.yaml": |
    - name: working-hours
      time_intervals:
        - weekdays: ["monday:friday"]
          times:
          - start_time: 06:00
            end_time: 13:00
metadata:
  namespace: babylon
  name: babylon-working-hours
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: babylon
    team: babylon
  name: babylon-apiserver
  namespace: babylon
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.64.1/32
        - ipBlock:
            cidr: 172.16.0.2/32
  podSelector:
    matchLabels:
      app: babylon
  policyTypes:
    - Egress