ingresses:
  - "https://babylon.dev.intern.nav.no"

log_level: "debug"
port: "8080"
armed: "false"
restart_threshold: "200"
resource_age: "10m"
tickrate: "1m"
notification_delay: "5m"
use_allowed_namespaces: "true"
allowed_namespaces: ""