ingresses:
  - "https://babylon.dev.intern.nav.no"

log_level: "info"
port: "8080"
armed: "false"
restart_threshold: "200"
resource_age: "10m"
tickrate: "1m"
notification_timeout: "5m"
linkerd_disabled: "true"