apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: babylon-alerter
  namespace: babylon
  labels:
    team: babylon
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: '#babylon-alerts'
      prependText: '<!here> | ' # this text will be prepended to the Slack alert title
  alerts:
    - alert: Deployment downscaled
      expr: 'increase(babylon_deployments_downscaled_total[5m]) > 1'
      for: 0s
      action: Read app logs (kubectl logs appname). Read Application events (kubectl descibe deployment appname)
      description: Babylon test-alert
      documentation: https://github.com/nais/babylon/README.md
      severity: warning