apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: babylon-alerter
  namespace: babylon
  labels:
    team: babylon
spec:
  route:
    group_by: [slack_channel]
  receivers: # receivers for all alerts below
    slack:
      channel: '\{{ index ((index .Alerts 0).Labels) "slack_channel" }}'
      icon_emoji: ':farmer:'
      send_resolved: false
      username: Babylon - Testing
  alerts:
    - alert: Deployment rolled back
      expr: 'increase(babylon_deployment_rollbacks_total[5m]) > 1'
      for: 0s
      action: |
        Read app logs (kubectl logs appname).
        Read Application events (kubectl describe deployment appname)
      description: |
        THIS IS A TEST OF BABYLON'S NOTIFICATION SYSTEM. PLEASE IGNORE THIS MESSAGE.
        However, we have detected an error in your nais deployment "\{{ $labels.deployment }}".
        Rolling back from \{{ $labels.previousDockerHash }} to \{{ $labels.currentDockerHash }}.
        (You might want to turn it off and on again, or rollback :oldmanyellsatcloud:)
      # description: Babylon rolled back \{{ $labels.deployment }} due to it failing with error `ImagePullBackOff`
      documentation: https://github.com/nais/babylon/README.md
      severity: warning