name: build

on: push

env:
  docker_image: ghcr.io/nais/babylon:${{ github.sha }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: go test ./...

      - name: Build
        run: |
          docker image build --tag ${docker_image} .

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker push ${docker_image}