name: build

on: push

env:
  docker_image: ghcr.io/nais/babylon:${{ github.sha }}

jobs:
  check:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test

  docker:
    name: Build and push Docker image
    needs: check
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker image build --tag ${docker_image} .

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ${docker_image}

  deployToDev:
    name: Deploy to dev
    needs: docker
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev.yaml
          VAR: image=${{ env.docker_image }}
