name: build

on: push

env:
  docker_image: ghcr.io/nais/babylon:${{ github.sha }}

jobs:
  docker:
    name: Build and push Docker image
    needs: check
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker image build --tag ${docker_image} .

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ${docker_image}

  testing:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - name: Test
        run: go test ./...
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install kuttl
        run: |
          brew tap kudobuilder/tap
          brew install kuttl-cli

      - name: Start minikube
        run: minikube start --wait=all

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env --shell=bash)
          GOOS=linux CGO_ENABLED=0 go build -o babylon
          docker build -f Local.dockerfile -t babylon .

      - name: Run Integration Test
        run: kubectl kuttl test --timeout=300 --start-kind=false

      - name: Debug Test
        if: ${{ failure() }}
        run: kubectl logs -l app=babylon-test --namespace=babylon-test --tail=1000

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: integration-testing-logs-${{ github.sha}}
          path: kuttl-logs/

  deployToDev:
    name: Deploy to dev
    needs:
      - docker
      - integrationTest
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    strategy:
      fail-fast: false
      matrix:
        cluster:
          - dev-gcp
          - dev-fss
          - dev-sbs

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ matrix.cluster }}.yaml
          VAR: image=${{ env.docker_image }},cluster=${{ matrix.cluster }},aiven=true

  deployToProd:
    name: Deploy to prod
    needs: deployToDev
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    strategy:
      fail-fast: false
      matrix:
        cluster:
          - prod-gcp
          - prod-fss
          - prod-sbs

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to PROD
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ matrix.cluster }}.yaml
          VAR: image=${{ env.docker_image }},cluster=${{ matrix.cluster }}
