name: build

on: push

env:
  docker_image: ghcr.io/nais/babylon:${{ github.sha }}

jobs:
  check:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: go test ./...

  docker:
    name: Build and push Docker image
    needs: check
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker image build --tag ${docker_image} .

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ${docker_image}

  integrationTest:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install kuttl
        run: |
          brew tap kudobuilder/tap
          brew install kuttl-cli

      - name: Start minikube
        run: minikube start --wait=all

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env --shell=bash)
          docker build -t babylon .

      - name: Run Integration Test
        run: kubectl kuttl test --timeout=120 --start-kind=false

      - name: Debug Test
        if: ${{ failure() }}
        run: kubectl logs -l app=babylon --namespace=babylon-test --tail=1000

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: integration-testing-logs-${{ github.sha}}
          path: kuttl-logs/


  deployToDev:
    name: Deploy to dev
    needs:
      - docker
      - integrationTest
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"

    strategy:
      matrix:
        cluster:
          - dev-gcp
          - dev-fss
          - dev-sbs

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml,alerts/rollbackAlert.yaml
          VARS: .nais/dev.yaml
          VAR: image=${{ env.docker_image }}
